//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratornaya_WPF_N1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lid
    {
        public int ID { get; set; }
        public string NumberPhoneClient { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateCreateLid { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> DateCallLid { get; set; }
        public Nullable<int> DurationCall { get; set; }
        public string Comment { get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual User User { get; set; }
    }
}
